# Generated by Django 4.2.7 on 2024-01-17 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0002_alter_snippet_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='snippet',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
